# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# site settings
title: Thomas's blog
email: kitian616@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    Thomas Tian's Blog | 田琦的博客

baseurl: /blog # the subpath of your site, e.g. /blog
url: http://www.thomastian.com # the base hostname & protocol for your site

lang: zh # the language of your site
timezone: Asia/Shanghai

# navbar
nav_lists:
  - title: About
    url: /blog/about/

# author info
author: Thomas Tian
avata_url: http://7xpqpj.com1.z0.glb.clouddn.com/image/me/peitaiho.JPG
bio: 前端开发实习生，立志成为全栈开发者。
homepage_url: http://www.thomastian.com/blog/about/
twitter_username: kitian616
github_username:  kitian616
googleplus_username: 101827554735084402671
weibo_username: 234695683
douban_username: kitian616

# google analytics
ga_tracking_id: UA-71907556-1
# comment
duoshuo_shortname: thomas-blog
# leancloud vies
app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
app_key: Mzf5m9skSwYVWVXhGiYMNyXs
app_class: ThomasBlog
# site github reop url
github_repo: blog
github_repo_tree: gh-pages

# paginate
paginate: 7
paginate_path: /page:num

# Basic settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
permalink: date
destination: ./_site/blog

#plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# server
#server_url: "http://1.hitcounter.applinzi.com/"
server_url: "0.0.0.0"
debug: false
